# Generated by Django 2.1.5 on 2019-02-02 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_level',
            field=models.CharField(choices=[('admin', 'Administrator'), ('vendor', 'Vendor'), ('member', 'Member')], default='member', max_length=120),
        ),
    ]
