# Generated by Django 2.1.5 on 2019-02-02 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_user_level'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='user_level',
            new_name='level',
        ),
    ]
