# Generated by Django 2.1.5 on 2019-02-02 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20190202_0756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='level',
            field=models.CharField(choices=[('admin', 'Administrator'), ('staff', 'Staff'), ('vendor', 'Vendor'), ('member', 'Member')], default='member', max_length=120),
        ),
    ]
