# Generated by Django 2.1.5 on 2019-04-19 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_vendorterm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendorterm',
            name='description',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
    ]
