# Generated by Django 2.1.5 on 2019-04-19 23:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20190419_2213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendorterm',
            name='userId',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Vendor ID'),
            preserve_default=False,
        ),
    ]
