# Generated by Django 2.1.5 on 2019-04-21 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20190419_2305'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bip39',
            field=models.TextField(blank=True, null=True),
        ),
    ]
