# Generated by Django 2.1.5 on 2019-04-30 15:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_vendorfavorite'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='trusts',
            field=models.ManyToManyField(blank=True, related_name='_user_trusts_+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='user',
            name='untrusts',
            field=models.ManyToManyField(blank=True, related_name='_user_untrusts_+', to=settings.AUTH_USER_MODEL),
        ),
    ]
