# Generated by Django 2.1.5 on 2019-05-03 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0002_ticket_ticket_replay'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='read',
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='read',
            field=models.BooleanField(default=False),
        ),
    ]
