# Generated by Django 2.1.7 on 2019-04-08 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20190409_0129'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='check',
            field=models.BooleanField(default=False),
        ),
    ]
