# Generated by Django 2.1.7 on 2019-04-09 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_message_check'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='create',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='update',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
