# Generated by Django 2.1.7 on 2019-04-09 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20190409_1108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='create',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
