# Generated by Django 2.1.5 on 2019-04-28 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20190428_1607'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='receiver_removed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='message',
            name='sender_removed',
            field=models.BooleanField(default=False),
        ),
    ]
