# Generated by Django 2.1.5 on 2019-05-02 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20190428_1726'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='payout_address',
            field=models.CharField(default='', max_length=100),
        ),
    ]
