# Generated by Django 2.1.5 on 2019-01-09 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(blank=True, null=True)),
                ('address', models.CharField(default='none', max_length=100)),
                ('amount_expected', models.DecimalField(decimal_places=8, max_digits=20)),
                ('amount_received', models.DecimalField(decimal_places=8, max_digits=20)),
                ('status', models.CharField(default='0', max_length=5)),
                ('author', models.CharField(default='none', max_length=100)),
                ('to', models.TextField(default='admin')),
            ],
        ),
    ]
