# Generated by Django 2.1.5 on 2019-01-09 21:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_pay'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pay',
            name='to',
        ),
    ]
