# Generated by Django 2.1.5 on 2019-01-12 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_auto_20190111_1711'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pay',
            name='address',
            field=models.TextField(default='none', max_length=3000),
        ),
    ]
