# Generated by Django 2.1.5 on 2019-01-12 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_auto_20190112_1508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='address',
            field=models.TextField(max_length=3000),
        ),
        migrations.AlterField(
            model_name='pay',
            name='address',
            field=models.CharField(max_length=300),
        ),
    ]
