# Generated by Django 2.1.7 on 2019-04-09 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_auto_20190112_1538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='paid',
            field=models.CharField(default='0', max_length=5),
        ),
    ]
