# Generated by Django 2.1.7 on 2019-04-09 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_auto_20190409_1136'),
    ]

    operations = [
        migrations.AddField(
            model_name='pay',
            name='btc_course',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=20),
        ),
    ]
