# Generated by Django 2.1.7 on 2019-04-11 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_pay_btc_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='pay',
            name='fee_amount',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='pay',
            name='vendor_amount',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=20),
        ),
    ]
